const projects = [
{title:"Stage - PEC Zwolle",cat:"Stage / Social Media",services:"Matchday visuals, Social design",tools:"Photoshop, Illustrator",cover:"images/Peczwolle_01.png",preview:"images/Peczwolle_01.png",gallery:["images/Peczwolle_01.png","images/Peczwolle_03.png","images/Peczwolle_10.png","images/Peczwolle_12.png","images/Peczwolle_15.png","images/Peczwolle_17.png","images/Peczwolle_21.png","images/Peczwolle_22.png","images/Peczwolle_24.gif","images/Peczwolle_25.png"],desc:"In het seizoen 2022/23 liep ik stage bij PEC Zwolle op de afdeling Media Marketing. Ik was verantwoordelijk voor matchday visuals, Wallpaper Wednesday, TikTok content en ontwerpen voor de VoetbalAcademie."},
{title:"Game Of Two Halves",cat:"Editorial design",services:"Book design, Typography",tools:"InDesign, Photoshop",cover:"images/Gameoftwohalves_01.png",preview:"images/Gameoftwohalves_01.png",gallery:["images/Gameoftwohalves_01.png","images/Gameoftwohalves_02.png","images/Gameoftwohalves_07.png","images/Gameoftwohalves_08.png","images/Gameoftwohalves_13.png","images/Gameoftwohalves_14.png","images/Gameoftwohalves_19.png","images/Gameoftwohalves_20.png","images/Gameoftwohalves_35.png","images/Gameoftwohalves_36.png","images/Gameoftwohalves_41.png","images/Gameoftwohalves_42.png","images/Gameoftwohalves_43.png","images/Gameoftwohalves_44.png"],desc:"Game of Two Halves is een boek vol de meest bekende sportcommentaar momenten. Op de ene pagina staat het commentaar, op de volgende pagina zie je de foto van dat moment. Met commentatoren als Peter Drury en Martin Taylor en citaten van spelers als Mbappe. Gemaakt vanuit mijn liefde voor voetbal."},
{title:"Loszand Festival 2024",cat:"Festival identiteit",services:"Social media design",tools:"Photoshop, Illustrator",cover:"images/Loszand_1.jpg",preview:"images/Loszand_1.jpg",gallery:["images/Loszand_1.jpg","images/Loszand_2.jpg","images/Loszand_3.jpg","images/Loszand_4.png","images/Loszand_5.png"],desc:"Loszand Festival vroeg mij social media visuals te ontwerpen. Het festival staat voor bier, zon, surfen en muziek - dat wilde ik terugbrengen in het ontwerp. Een kleurverloop van oranje zand naar blauw water, golven op de achtergrond als verwijzing naar het surfen en mensen die samenkomen. Het gekozen lettertype maakt het zomerse gevoel compleet."},
{title:"Liquid Liquor",cat:"Branding / label design",services:"Packaging design",tools:"Illustrator",cover:"images/Liqued Licour_1.png",preview:"images/Liqued Licour_1.png",gallery:["images/Liqued Licour_1.png","images/Liqued Licour_2.png","images/Liqued Licour_3.png","images/Liqued Licour_4.png"],desc:"Liquid Liquor vroeg mij een etiket te ontwerpen voor hun druivenlikeur. Het ontwerp kenmerkt zich door houtnerven als achtergrond, een kleurverloop van paars naar blauw en handgetekende druiven bovenaan en onderaan het etiket. Een warm en herkenbaar geheel."},
{title:"Insanity",cat:"Festival social media",services:"Concept design",tools:"Photoshop",cover:"images/Insanity_1.png",preview:"images/Insanity_1.png",gallery:["images/Insanity_1.png","images/Insanity_2.jpg","images/Insanity_3.png","images/Insanity_4.png","images/Insanity_5.png"],desc:"Insanity Festival in Westland vroeg mij een visueel concept te ontwikkelen voor hun social media. Ik transformeerde het logo naar een 3D-versie en combineerde dit met een ruimteachtergrond en een woestijnlandschap. Door te spelen met lagen en losse elementen in Photoshop ontstond uiteindelijk dit geheel."},
{title:"Ines Administratie",cat:"Logo design",services:"Brand identity",tools:"Illustrator",cover:"images/Inesadministratie_1.png",preview:"images/Inesadministratie_1.png",gallery:["images/Inesadministratie_1.png"],desc:"Ines Administratie vroeg mij een bedrijfslogo te ontwerpen. Na een korte briefing werd al snel duidelijk dat de I van Ines een centrale rol moest spelen in het ontwerp. Met een kleurverloop als extra detail zijn we samen tot een logo gekomen waar de klant erg blij mee is."},
{title:"EVNTP",cat:"Editorial design",services:"Magazine design",tools:"InDesign",cover:"images/evntp_01.png",preview:"images/evntp_01.png",gallery:["images/evntp_01.png","images/evntp_20.png","images/evntp_21.png","images/evntp_22.png","images/evntp_23.png","images/evntp_24.png","images/evntp_25.png","images/evntp_30.png","images/evntp_31.png"],desc:"Afstudeerproject waarbij ik onderzoek deed naar duurzamere festivalmunten en dit presenteerde in de vorm van een magazine."},
{title:"Fight The Evil (Savellix)",cat:"Music artwork",services:"Album cover",tools:"Photoshop",cover:"images/fighttheevil_01.png",preview:"images/fighttheevil_01.png",gallery:["images/fighttheevil_01.png","images/fighttheevil_02.png","images/fighttheevil_03.png","images/fighttheevil_27.png","images/fighttheevil_28.png"],desc:"Savellix, ook wel bekend als Maurice, is een Nederlandse DJ en producer. Na het succes van onze eerste samenwerking vroeg hij mij opnieuw een albumhoes te ontwerpen voor zijn tweede single Fight the Evil. Ik heb dit met veel plezier gedaan en het resultaat is een donkere en krachtige cover die goed bij de energie van het nummer past. De single is nu te beluisteren op Spotify."},
{title:"Rise And Unite",cat:"Music artwork",services:"Album cover",tools:"Photoshop",cover:"images/Riseandunite_01.png",preview:"images/Riseandunite_01.png",gallery:["images/Riseandunite_01.png","images/Riseandunite_02.jpg","images/Riseandunite_03.png","images/Riseandunite_04.jpeg","images/Riseandunite_05.jpeg","images/Riseandunite_06.jpeg","images/Riseandunite_07.jpeg","images/Riseandunite_08.jpeg","images/Riseandunite_09.jpeg","images/Riseandunite_10.jpeg","images/Riseandunite_11.jpeg","images/Riseandunite_12.jpeg","images/Riseandunite_13.jpeg","images/Riseandunite_14.jpeg","images/Riseandunite_15.jpeg","images/Riseandunite_16.jpeg","images/Riseandunite_17.jpeg","images/Riseandunite_18.png","images/Riseandunite_19.png"],desc:"Savellix, ook wel bekend als Maurice, is een Nederlandse DJ en producer. Voor zijn debuutsingle Rise and Unite (Insanity Anthem 2021) vroeg hij mij een albumhoes te ontwerpen. Het resultaat is een cover die de energie van het nummer goed weergeeft. De single is nu te beluisteren op Spotify."},
{title:"Jeugdweek Norschoten 2023",cat:"Huisstijl / Event",services:"Logo design, Drukwerk",tools:"Illustrator, Photoshop",cover:"images/Jeugdweek2023_1.png",preview:"images/Jeugdweek2023_1.png",gallery:["images/Jeugdweek2023_1.png","images/Jeugdweek2023_2.png","images/Jeugdweek2023_3.png"],desc:"Voor Jeugdweek Norschoten 2023 ontwierp ik de huisstijl rondom het thema Faith Airlines. Een reis langs bijbelverhalen uit verschillende continenten, vertaald naar een logo met wereldbol en vliegtuig en een bijpassende uitnodiging."},
{title:"Jeugdweek Norschoten 2024",cat:"Huisstijl / Event",services:"Logo design, Drukwerk",tools:"Illustrator, Photoshop",cover:"images/Jeugdweek2024_1.png",preview:"images/Jeugdweek2024_1.png",gallery:["images/Jeugdweek2024_1.png","images/Jeugdweek2024_2.jpg","images/Jeugdweek2024_3.jpg"],desc:"Voor Jeugdweek Norschoten 2024 ontwierp ik de huisstijl rondom het thema Faith on the Olympics, geïnspireerd op de Olympische Zomerspelen van dat jaar. Bijbelverhalen vertaald naar een olympisch jasje."}
]

function showHome(){document.querySelectorAll(".page").forEach(function(p){p.classList.remove("active")});document.getElementById("page-home").classList.add("active");history.pushState({page:"home"},"",location.pathname);window.scrollTo(0,0)}
function showPage(name){document.querySelectorAll(".page").forEach(function(p){p.classList.remove("active")});document.getElementById("page-"+name).classList.add("active");history.pushState({page:name},"",location.pathname);window.scrollTo(0,0)}
function openProject(i){var p=projects[i];document.getElementById("proj-h").innerText=p.title;document.getElementById("ps-title").innerText=p.title;document.getElementById("ps-cat").innerText=p.cat;document.getElementById("ps-serv").innerText=p.services;document.getElementById("ps-tools").innerText=p.tools;document.getElementById("proj-desc").innerText=p.desc;document.getElementById("proj-cover").src=p.cover;var grid=document.getElementById("gal-grid");grid.innerHTML="";p.gallery.forEach(function(img,idx){var item=document.createElement("div");item.className=idx===0?"gi wide":"gi";item.innerHTML='<img loading="lazy" src="'+img+'">';grid.appendChild(item)});document.querySelectorAll(".page").forEach(function(p){p.classList.remove("active")});document.getElementById("page-project").classList.add("active");history.pushState({page:"project",index:i},"",location.pathname);window.scrollTo(0,0)}

var navLogo=document.getElementById("nav-logo");
var navHome=document.getElementById("nav-home");
var navWork=document.getElementById("nav-work");
var navAbout=document.getElementById("nav-about");
var navContact=document.getElementById("nav-contact");
var backBtn=document.getElementById("back-btn");
var aboutTeaser=document.getElementById("about-teaser");

if(navLogo)navLogo.onclick=function(e){e.preventDefault();showHome()};
if(navHome)navHome.onclick=function(){showHome()};
if(navWork)navWork.onclick=function(){showHome();setTimeout(function(){document.getElementById("wa").scrollIntoView({behavior:"smooth"})},80)};
if(navAbout)navAbout.onclick=function(){showPage("about")};
if(navContact)navContact.onclick=function(){showHome();setTimeout(function(){document.getElementById("ca").scrollIntoView({behavior:"smooth"})},80)};
if(backBtn)backBtn.onclick=function(){showHome()};
if(aboutTeaser)aboutTeaser.onclick=function(){showPage("about")};

var list=document.getElementById("project-list");
projects.forEach(function(p,i){var row=document.createElement("div");row.className="p-row";row.innerHTML='<div class="p-num">'+String(i+1).padStart(2,"0")+'</div><div class="p-title">'+p.title+'</div><div class="p-cat">'+p.cat+"</div>";row.onclick=function(){openProject(i)};list.appendChild(row)});

var preview=document.getElementById("preview");
var previewImg=document.getElementById("preview-img");
document.querySelectorAll(".p-row").forEach(function(row,i){row.addEventListener("mouseenter",function(){previewImg.src=projects[i].preview;preview.classList.add("visible")});row.addEventListener("mouseleave",function(){preview.classList.remove("visible")});row.addEventListener("mousemove",function(e){preview.style.left=e.clientX+"px";preview.style.top=e.clientY+"px"})});

window.addEventListener("popstate",function(e){if(!e.state||e.state.page==="home"){document.querySelectorAll(".page").forEach(function(p){p.classList.remove("active")});document.getElementById("page-home").classList.add("active");window.scrollTo(0,0);return}if(e.state.page==="about"){document.querySelectorAll(".page").forEach(function(p){p.classList.remove("active")});document.getElementById("page-about").classList.add("active");window.scrollTo(0,0)}else if(e.state.page==="project"){openProject(e.state.index)}});

history.replaceState({page:"home"},"",location.pathname);

var cur=document.getElementById("cur");
var curF=document.getElementById("cur-f");
var mx=0,my=0,fx=0,fy=0;
document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;cur.style.left=mx+"px";cur.style.top=my+"px"});
function animateCursor(){fx+=(mx-fx)*0.18;fy+=(my-fy)*0.18;curF.style.left=fx+"px";curF.style.top=fy+"px";requestAnimationFrame(animateCursor)}
animateCursor();
document.querySelectorAll("a, button, .p-row, .about-teaser").forEach(function(el){el.addEventListener("mouseenter",function(){cur.classList.add("big")});el.addEventListener("mouseleave",function(){cur.classList.remove("big")})});
